In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
from rdkit import Chem 
from rdkit.Chem import Descriptors
from rdkit.Chem import AllChem

# 1. Read Training Dataset and Test Dataset

In [57]:
training_df= pd.read_csv("training_smiles.csv")

In [58]:
test_df= pd.read_csv("test_smiles.csv")

# 2. Convert SMILE String into Molecule Object

In [59]:
training_df['mol'] = training_df['SMILES'].apply(lambda x: Chem.MolFromSmiles(x)) 

[13:24:49] WARNING: not removing hydrogen atom without neighbors


In [60]:
test_df['mol'] = test_df['SMILES'].apply(lambda x: Chem.MolFromSmiles(x)) 

[13:25:40] WARNING: not removing hydrogen atom without neighbors


# 3. Extract Morgan Fingerprint Features (vectors)

In [62]:
Morgan_train = training_df.copy()
training_fp = np.zeros((training_df.index.size,124))
for i in range(training_df.index.size):
    training_fp[i] = np.array(AllChem.GetMorganFingerprintAsBitVect(training_df['mol'][i],1,nBits=124))
print(training_fp)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]]


In [63]:
for j in range(training_fp.shape[1]):
    Morgan_train["fp{}".format(j)] = training_fp[:,j]
Morgan_train.drop(columns=["INDEX", "SMILES", "mol"], inplace = True)

C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\966757706.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Morgan_train["fp{}".format(j)] = training_fp[:,j]
C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\966757706.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Morgan_train["fp{}".format(j)] = training_fp[:,j]
C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\966757706.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performa

C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\966757706.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Morgan_train["fp{}".format(j)] = training_fp[:,j]
C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\966757706.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Morgan_train["fp{}".format(j)] = training_fp[:,j]
C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\966757706.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performa

In [64]:
Morgan_test = test_df.copy()
test_fp = np.zeros((test_df.index.size,124))
for i in range(test_df.index.size):
    test_fp[i] = np.array(AllChem.GetMorganFingerprintAsBitVect(test_df['mol'][i],1,nBits=124))
print(test_fp)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [65]:
for j in range(test_fp.shape[1]):
    Morgan_test["fp{}".format(j)] = test_fp[:,j]
Morgan_test.drop(columns=["INDEX", "SMILES", "mol"], inplace = True)

C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\1228905965.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Morgan_test["fp{}".format(j)] = test_fp[:,j]
C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\1228905965.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Morgan_test["fp{}".format(j)] = test_fp[:,j]
C:\Users\Yuhan\AppData\Local\Temp\ipykernel_131756\1228905965.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  C

In [66]:
print(Morgan_train)

        ACTIVE  fp0  fp1  fp2  fp3  fp4  fp5  fp6  fp7  fp8  ...  fp114  \
0          0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
1          0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  ...    0.0   
2          0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  ...    1.0   
3          0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...    0.0   
4          0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
156253     0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  ...    0.0   
156254     0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  ...    0.0   
156255     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
156256     0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...    0.0   
156257     0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...    0.0   

        fp115  fp116  fp117  fp118  fp119  fp120  fp121  fp122  fp123  
0         0.0    0.0    0.0

In [67]:
print(Morgan_test)

       fp0  fp1  fp2  fp3  fp4  fp5  fp6  fp7  fp8  fp9  ...  fp114  fp115  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  ...    0.0    0.0   
1      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
3      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4      0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
52081  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
52082  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
52083  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
52084  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  ...    0.0    0.0   
52085  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

       fp116  fp117  fp118  fp119  fp120  fp121  fp122  fp123  

# 4. Save Feature Sets into csv Files

In [68]:
Morgan_train.to_csv("Morgan_train.csv")

In [69]:
Morgan_test.to_csv("Morgan_test.csv")